name: terraserve_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  country_picker: ^2.0.26
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  visibility_detector: ^0.4.0 
  provider: ^6.1.2
  dio: ^5.4.3+1
  latlong2: ^0.9.0
  shared_preferences: ^2.2.2
  
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_map: ^6.1.0
  image_picker: ^1.1.2
  camera: ^0.11.2
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
